#!/bin/sh

sxhkd &>/home/neko/sxkhd.log &
bspc monitor -d home music study mail basement VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           2
bspc config active_border_color #3269a8
bspc config normal_border_color #eb4034

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
automatic_scheme spiral

xrandr --output eDP-1 --mode 2048x1152 &
sudo mount --bind /home/neko/projects/programming/web/hwt/frontend /srv/http
~/.fehbg
picom --experimental-backends -b &
$HOME/.config/polybar/launch.sh &
~/bin/setupkeyboard.sh &
termite &
